### PR TITLE
fix: remove stream add/remove methods from connection interface

### LINKED ISSUE #1855: Remove Stream methods from `Connection` interface
Following up from the discussion [here](https://github.com/libp2p/js-libp2p/pull/1612#issuecomment-1487181271) the muxers should be ultimately responsible for managing streams as opposed to the connections themselves

### PR DESCRIPTION
**Pull request by tabcat**
remove (add|remove)Stream from connection interface

remove (add|remove)Stream use from interface-compliance-tests

remove (add|remove)Stream from libp2p connection methods

remove (add|remove)Stream from libp2p upgrader methods

Closes #1855

### CODE REVIEW

**Comment by tabcat** [comment]
should this be a breaking change?

**Comment by tabcat** [comment]
This is more prevalent than I thought. Going to close for now and maybe open this or another pr later.

**Comment by maschad** [comment]
I've converted it to a draft to avoid unnecessary notifications, feel free to re-open once you feel it ready for review.

File: packages/interface-compliance-tests/src/connection/index.ts [hunk 1]
```diff
@@ -127,7 +127,7 @@ export default (test: TestSetup<Connection>): void => {
       it.skip('should track inbound streams', async () => {
         // Add an remotely opened stream
         const stream = stubInterface<Stream>()
-        connection.addStream(stream)
+        // connection.addStream(stream)
         expect(stream).to.have.property('direction', 'inbound')
       })
```
Comment (tabcat) [inline packages/interface-compliance-tests/src/connection/index.ts:132]: could this test just be removed?

File: packages/interface-compliance-tests/src/connection/index.ts [hunk 2]
```diff
@@ -127,7 +127,7 @@ export default (test: TestSetup<Connection>): void => {
       it.skip('should track inbound streams', async () => {
         // Add an remotely opened stream
         const stream = stubInterface<Stream>()
-        connection.addStream(stream)
+        stream.direction = 'inbound'
```
Comment (tabcat) [inline packages/interface-compliance-tests/src/connection/index.ts:130]: all .addStream was doing here is `stream.direction = 'inbound'`. can this test just be removed since it was already skipped?

Comment (maschad) [reply packages/interface-compliance-tests/src/connection/index.ts:130]: Yes this can be removed

**Review by maschad — APPROVED** [review]
lgtm

**Comment by achingbrain** [comment]
@maschad because methods were removed from a public API this is a breaking change.

I have updated the issue description to use a commit override.
