### PR TITLE
fix: registrar is not calling topology on peer reconnect

### LINKED ISSUE #1496: Connection drop causes pubsub to stop working.
- **Version**: 0.40.0

- **Platform**:  MacOS, Node v16.14.0

- **Subsystem**: Pubsub, Relay, ConnectionManager

#### Description:

I have two peers - Alice and Bob, both connected to the same relay server and subscribed to the same topic. 

I need to find all peers subscribed to a given topic, e.g. I call `libp2p.pubsub.getSubscribers("my_topic")` from the Alice side and expect to see Bob's peer id in response.

When we run both peers the first time, everything works as expected - peers sees each other in topic subscribers. But when some of the peers reconnects (doesn't matter Alice or Bob), they does not see each other anymore. But if I restart one of the peers manually, everything works as expected until next reconnect.

I am using `gossibsub` for pubsub, but also tried `floodsub` with the same result.

My issue is very similar to #658.

#### Steps to reproduce the error:

I created [reproduction repository](https://github.com/AlexMesser/pubsub-issue-reproduction) for better explanation.

### PR DESCRIPTION
**Pull request by mpetrunic**
If the peer reconnects with the same protocols, `change:protocols` is not emitted and topology `onConnect` callbacks are not invoked. This adds listening to connect events in the registrar and checks if we already know protocols for peers before calling the topology `onConnect` callback.

resolves #1496

### CODE REVIEW

**Comment by mpetrunic** [comment]
Seems like regression as it was once fixed in same manner: https://github.com/libp2p/js-libp2p-interfaces/pull/54/files

File: src/registrar.ts [hunk 1]
```diff
@@ -176,12 +178,38 @@ export class DefaultRegistrar implements Registrar {
       })
   }
 
+  /**
+   * On peer connected if we already have his protocols. Usually used for reconnects
```
Comment (achingbrain) [inline src/registrar.ts:182]:
```suggestion
   * On peer connected if we already have their protocols. Usually used for reconnects
```

**Review by achingbrain — APPROVED** [review]

**Comment by AlexMesser** [comment]
Thanks for the fix, hope new npm version will be released soon.

**Comment by achingbrain** [comment]
Likely Monday morning - in the interim you can test with the rc with `npm i libp2p@next`.
