### PR TITLE
Fix type definition for v0.35.6

### LINKED ISSUE #1073: Typescript build error
- **Version**:
0.35.6

- **Platform**:
Mac OS X

- **Subsystem**:

#### Severity:
High - Lodestar could not compile

#### Description:
Compilation error when using v0.35.6 with lodestar:

```
@chainsafe/lodestar: $ tsc -p tsconfig.build.json
@chainsafe/lodestar: ../../node_modules/libp2p/dist/src/dialer/index.d.ts:168:18 - error TS2304: Cannot find name 'DialRequest'.
@chainsafe/lodestar: 168     dialRequest: DialRequest;
@chainsafe/lodestar:                      ~~~~~~~~~~~
@chainsafe/lodestar: ../../node_modules/libp2p/dist/src/dialer/index.d.ts:169:17 - error TS2304: Cannot find name 'TimeoutController'.
@chainsafe/lodestar: 169     controller: TimeoutController;
@chainsafe/lodestar:                     ~~~~~~~~~~~~~~~~~
@chainsafe/lodestar: ../../node_modules/libp2p/dist/src/index.d.ts:413:37 - error TS2503: Cannot find namespace 'PersistentPeerStore'.
@chainsafe/lodestar: 413     peerStore?: (PeerStoreOptions & PersistentPeerStore.PersistentPeerStoreOptions) | undefined;
@chainsafe/lodestar:                                         ~~~~~~~~~~~~~~~~~~~
@chainsafe/lodestar: ../../node_modules/libp2p/dist/src/metrics/stats.d.ts:18:23 - error TS2304: Cannot find name 'Big'.
@chainsafe/lodestar: 18         dataReceived: Big;
@chainsafe/lodestar:                          ~~~
@chainsafe/lodestar: ../../node_modules/libp2p/dist/src/metrics/stats.d.ts:19:19 - error TS2304: Cannot find name 'Big'.
@chainsafe/lodestar: 19         dataSent: Big;
@chainsafe/lodestar:                      ~~~
@chainsafe/lodestar: ../../node_modules/libp2p/dist/src/metrics/stats.d.ts:60:23 - error TS2304: Cannot find name 'Big'.
@chainsafe/lodestar: 60         dataReceived: Big;
@chainsafe/lodestar:                          ~~~
@chainsafe/lodestar: ../../node_modules/libp2p/dist/src/metrics/stats.d.ts:61:19 - error TS2304: Cannot find name 'Big'.
@chainsafe/lodestar: 61         dataSent: Big;
@chainsafe/lodestar:                      ~~~
@chainsafe/lodestar: src/chain/chain.ts:85:1 - error TS7008: Member '1' implicitly has an 'any' type.
@chainsafe/lodestar: 85 1
@chainsafe/lodestar:    ~
```

#### Steps to reproduce the error:
We can see the same issue even in the `dist/src` folder of libp2p

### PR DESCRIPTION
**Pull request by tuyennhv**
**Motivation**
+ I'd like to fix tsc compilation error when using v0.35.6 for lodestar

**Description**
Closes #1073

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -110,7 +112,7 @@ const { updateSelfPeerRecord } = require('./record/utils')
  * @property {KeychainOptions & import('./keychain/index').KeychainOptions} [keychain]
  * @property {MetricsOptions & import('./metrics').MetricsOptions} [metrics]
  * @property {import('./peer-routing').PeerRoutingOptions} [peerRouting]
- * @property {PeerStoreOptions & import('./peer-store/persistent').PersistentPeerStoreOptions} [peerStore]
+ * @property {PeerStoreOptions & PersistentPeerStoreOptions} [peerStore]
```
Comment (vasco-santos) [inline src/index.js:115]: Why can't we use the types defined in https://github.com/libp2p/js-libp2p/blob/3bed7b4cb25157191b29d4b058cb6222eb3bfcd7/src/peer-store/persistent/index.js#L35 instead of duplicating them?

Comment (tuyennhv) [reply src/index.js:115]: I suppose that's an issue with `pbjs` when we use that along with `const PersistentPeerStore = require('./peer-store/persistent')` at the beginning, it'd generate `PersistentPeerStore.PersistentPeerStoreOptions` and cause the error 

```
@chainsafe/lodestar: ../../node_modules/libp2p/dist/src/index.d.ts:413:37 - error TS2503: Cannot find namespace 'PersistentPeerStore'.
@chainsafe/lodestar: 413     peerStore?: (PeerStoreOptions & PersistentPeerStore.PersistentPeerStoreOptions) | undefined;
```

this does not look fancy but I can't find other ways to get through that, any suggestions @vasco-santos ? Upgrading to the latest version of `pbjs` did not help

Comment (vasco-santos) [reply src/index.js:115]: ok, let's keep it. It is just a property

**Review by vasco-santos — APPROVED** [review]
