### PR TITLE
fix(@libp2p/utils): switch to @chainsafe/is-ip

### LINKED ISSUE #1926: switch to @chainsafe/is-ip (away from @achingbrain/ip-address)
Is there a reason why we're still using `@achingbrain/ip-address`, or even ip-address, when it's outdated? There seem to be better and more up to date alternatives: https://npmtrends.com/ip-vs-ip-address-vs-ipaddr.js. Though maybe they don't do everything we need them to?

One of `ip-address` 's dependencies, `jsbn`, is very stale and very underused in comparison to it's competitors: https://npmtrends.com/bignumber.js-vs-bn-vs-bn.js-vs-jsbn

There is also the native BigInt which has been around for a while: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt

We only seem to have a very small surface area for each here: 

* ip-address - https://github.com/search?q=repo%3Alibp2p%2Fjs-libp2p+ip-address&type=code
* jsbn - https://github.com/search?q=repo%3Alibp2p%2Fjs-libp2p+jsbn&type=code

I also seem to remember some concerns around node-forge being used in js-libp2p and this may be another place where we could reduce our ties to it.

---

I'm not aware of the nuances but generally if a project leaves a PR that we need (https://github.com/beaugunderson/ip-address/pull/148) untouched for over a year (it's going on 2), and we still don't have a permanent place to modify code for our patched version, we should probably think about migrating, or publishing our version.

cc @achingbrain. related to https://github.com/ipfs/helia/issues/73#issuecomment-1644024103

### PR DESCRIPTION
**Pull request by achingbrain**
The `@achingbrain/ip-address` module is a fork of `ip-address` which seems to have dependencies on older modules that break modern runtimes like react native.

`@Chainsafe/is-ip` does not have these limitations so switch to that.

Fixes #1926

### CODE REVIEW

File: packages/utils/src/ip-port-to-multiaddr.ts [hunk 1]
```diff
@@ -27,21 +27,15 @@ export function ipPortToMultiaddr (ip: string, port: number | string): Multiaddr
...
-    return ip6.is4()
-      ? multiaddr(`/ip4/${ip6.to4().correctForm()}/tcp/${port}`)
-      : multiaddr(`/ip6/${ip}/tcp/${port}`)
-  } catch (err) {
-    const errMsg = `invalid ip:port for creating a multiaddr: ${ip}:${port}`
-    log.error(errMsg)
-    throw new CodeError(errMsg, Errors.ERR_INVALID_IP)
   }
+
+  if (isIPv6(ip)) {
```
Comment (achingbrain) [inline packages/utils/src/ip-port-to-multiaddr.ts:34]: `@chainsafe/is-ip` doesn't support detecting [IPv4 in IPv6 addresses](https://www.ibm.com/docs/en/ts4500-tape-library?topic=functionality-ipv4-ipv6-address-formats) so we lose support for returning an `IPv4` address in this case.

Node.js recognises these sorts of addresses as `IPv6` so I don't know if this is a problem or not.

E.g.:


```console
% node
Welcome to Node.js v18.14.0.
Type ".help" for more information.
> const net = require('net')
undefined
> net.isIP('0:0:0:0:0:0:101.45.75.219')
6
```

File: packages/utils/test/ip-port-to-multiaddr.spec.ts [hunk 2]
```diff
@@ -19,7 +19,7 @@ describe('IP and port to Multiaddr', () => {
   it('creates multiaddr from valid IPv4 in IPv6 IP and port', () => {
     const ip = '0:0:0:0:0:0:101.45.75.219'
     const port = '9090'
-    expect(ipPortToMultiaddr(ip, port).toString()).to.equal(`/ip4/101.45.75.219/tcp/${port}`)
+    expect(ipPortToMultiaddr(ip, port).toString()).to.equal(`/ip6/::652d:4bdb/tcp/${port}`)
```
Comment (achingbrain) [inline packages/utils/test/ip-port-to-multiaddr.spec.ts:22]: `@chainsafe/is-ip` doesn't support detecting [IPv4 in IPv6 addresses](https://www.ibm.com/docs/en/ts4500-tape-library?topic=functionality-ipv4-ipv6-address-formats) so we lose support for returning an `IPv4` address in this case.

Node.js recognises these sorts of addresses as `IPv6` so I don't know if this is a problem or not.

E.g.:


```console
% node
Welcome to Node.js v18.14.0.
Type ".help" for more information.
> const net = require('net')
undefined
> net.isIP('0:0:0:0:0:0:101.45.75.219')
6
```

File: packages/utils/src/ip-port-to-multiaddr.ts [hunk 3]
```diff
@@ -27,21 +27,15 @@ export function ipPortToMultiaddr (ip: string, port: number | string): Multiaddr
...
+    return multiaddr(`/ip6/${ip}/tcp/${port}`)
+  }
+
+  const errMsg = `invalid ip:port for creating a multiaddr: ${ip}:${port}`
+  log.error(errMsg)
+  throw new CodeError(errMsg, Errors.ERR_INVALID_IP)
```
Comment (SgtPooki) [inline packages/utils/src/ip-port-to-multiaddr.ts:40]: This is so much cleaner than the previous code

File: packages/utils/test/ip-port-to-multiaddr.spec.ts (hunk 2 above)
Comment (SgtPooki) [reply packages/utils/test/ip-port-to-multiaddr.spec.ts:22]: We should be able to detect dual ipv6 addresses by simply testing for octects (or their delimiter, a period)

Comment (SgtPooki) [reply packages/utils/test/ip-port-to-multiaddr.spec.ts:22]: I need to test the browser usecase. if this is showing as ipv6, we should be able to just wrap in brackets for URL construction.

**Review by SgtPooki — COMMENTED** [review]
Need to confirm dualIpv6 support in browser before approving

File: packages/utils/test/ip-port-to-multiaddr.spec.ts (hunk 2 above)
Comment (SgtPooki) [reply packages/utils/test/ip-port-to-multiaddr.spec.ts:22]:
```bash
> new URL('http://[::101.45.75.219]')
URL {
  href: 'http://[::652d:4bdb]/',
  origin: 'http://[::652d:4bdb]',
  protocol: 'http:',
  username: '',
  password: '',
  host: '[::652d:4bdb]',
  hostname: '[::652d:4bdb]',
  port: '',
  pathname: '/',
  search: '',
  searchParams: URLSearchParams {},
  hash: ''
}
```

**Review by SgtPooki — APPROVED** [review]

**Comment by SgtPooki** [comment]
I gave approval, but I expect this will break one scenario: consumers of dualIpv6 addresses that don't support ipv6 used to get an ipv4 multiaddr they could use; they won't anymore.

**Comment by achingbrain** [comment]
It seems weird to me that we’d accept a v6 address and return a v4 one, not what I would expect.
