### PR TITLE
fix: interpret circuit relay expiry as seconds

### LINKED ISSUE #1635: circuitRelayTransport repeatedly reconnecting to relay
- **Version**:

- **Platform**:

Linux archlinux 5.15.59-2-lts #1 SMP Sat, 06 Aug 2022 21:34:17 +0000 x86_64 GNU/Linux

- **Subsystem**:

Relay

#### Description:

- Connected a libp2p node to a Go libp2p node serving circuit v2 relay.
- A relay slot was repeatedly being reserved on the Go relay (looked like an infinite loop).
- It should only reserve the slot once and wait for a timeout to trigger.

#### Steps to reproduce the error:

Instantiate the go relay with `GOLOG_LOG_LEVEL=debug go run main.go`. It should print out a websocket multiaddr.
```go
package main

import (
	"crypto/rand"
	"fmt"

	"github.com/libp2p/go-libp2p"
	"github.com/libp2p/go-libp2p/core/crypto"
	"github.com/libp2p/go-libp2p/core/host"

	// "github.com/libp2p/go-libp2p/core/peer"
	"github.com/libp2p/go-libp2p/p2p/muxer/mplex"
	relay "github.com/libp2p/go-libp2p/p2p/protocol/circuitv2/relay"
	ma "github.com/multiformats/go-multiaddr"
)

func main() {
	makeRelayV2()
	select {}
}

func makeRelayV2() host.Host {
	r := rand.Reader
	// Generate a key pair for this host. We will use it at least
	// to obtain a valid host ID.
	priv, _, err := crypto.GenerateKeyPairWithReader(crypto.RSA, 2048, r)
	if err != nil {
		panic(err)
	}

	opts := []libp2p.Option{
		libp2p.DefaultTransports,
		libp2p.ListenAddrStrings(
			"/ip4/0.0.0.0/tcp/4003/ws",
		),
		libp2p.Muxer("/mplex/6.7.0", mplex.DefaultTransport),
		libp2p.Identity(priv),
		libp2p.EnableRelay(),
	}

	host, err := libp2p.New(opts...)
	if err != nil {
		panic(err)
	}

	_, err = relay.New(host)
	if err != nil {
		panic(err)
	}

	// fmt.Println(host.Mux().Protocols())

	for _, addr := range host.Addrs() {
		a, err := ma.NewMultiaddr(fmt.Sprintf("/p2p/%s", host.ID().Pretty()))
		if err != nil {
			panic(err)
		}
		fmt.Println("p2p addr: ", addr.Encapsulate(a))
	}
	return host
}
```

Instantiate the node process with `DEBUG=libp2p:circuit-relay:* node index.js`
```js
import { noise } from "@chainsafe/libp2p-noise";
import { mplex } from "@libp2p/mplex";
import { webSockets } from "@libp2p/websockets";
import * as filters from  "@libp2p/websockets/filters";
import { createLibp2p } from "libp2p";
import { circuitRelayTransport } from "libp2p/circuit-relay";
import { multiaddr } from "@multiformats/multiaddr";

const node = await createLibp2p({
    transports: [
        webSockets({
            filters: filters.all,
        }),
        circuitRelayTransport({
            discoverRelays: 1,
        }),
    ],
    connectionEncryption: [noise()],
    streamMuxers: [mplex()],
});


await node.dial(multiaddr(process.argv[2]))

```
The node and go processes should keep logging a new circuit relay reservation.

### PR DESCRIPTION
**Pull request by ckousik**
This fixes #1635 which causes the circuit relay to repeatedly connect to a discovered relay. If the relay returns connection expiration in seconds, we get a negative ttl when calculating
`expiration - new Date().getTime()`.
This caused the `addRelay` function to set the timeout at 0ms. This timeout instantly triggers and calls `addRelay` recursively.

### CODE REVIEW

File: src/circuit/transport/reservation-store.ts [hunk 1]
```diff
@@ -162,13 +162,16 @@ export class ReservationStore extends EventEmitter<ReservationStoreEvents> imple
...
 
         const timeout = setTimeout(() => {
           this.addRelay(peerId, type).catch(err => {
             log.error('could not refresh reservation to relay %p', peerId, err)
           })
-        }, Math.max(expiration - REFRESH_TIMEOUT, 0))
+        },
+        // TODO: If we get an expiration of 0, this will keep calling
+        // addRelay
+        Math.max(expiration * 1000 - REFRESH_TIMEOUT, 0))
```
Comment (ckousik) [inline src/circuit/transport/reservation-store.ts:174]: could this cause a 32 bit overflow?

File: src/circuit/transport/reservation-store.ts [hunk 2]
```diff
@@ -131,7 +131,7 @@ export class ReservationStore extends EventEmitter<ReservationStoreEvents> imple
         const existingReservation = this.reservations.get(peerId)
 
         if (existingReservation != null) {
-          if (getExpiration(existingReservation.reservation.expire) > REFRESH_WINDOW) {
+          if (getExpirationSeconds(existingReservation.reservation.expire) > REFRESH_WINDOW) {
```
Comment (achingbrain) [inline src/circuit/transport/reservation-store.ts:134]: It looks like you're comparing seconds to milliseconds here?

File: src/circuit/utils.ts [hunk 3]
```diff
@@ -115,6 +115,7 @@ export async function namespaceToCid (namespace: string): Promise<CID> {
 /**
  * returns number of ms between now and expiration time
  */
-export function getExpiration (expireTime: bigint): number {
-  return Number(expireTime) - new Date().getTime()
+export function getExpirationSeconds (expireTime: bigint): number {
```
Comment (achingbrain) [inline src/circuit/utils.ts:118]: The comment still says it returns the number of ms but the function has been renamed to say it returns seconds.

File: src/circuit/utils.ts [hunk 4]
```diff
@@ -115,6 +115,7 @@ export async function namespaceToCid (namespace: string): Promise<CID> {
...
+  const currentTimeSeconds = ((new Date().getTime()) / 1000) | 0
+  return Number(expireTime) - currentTimeSeconds
```
Comment (achingbrain) [inline src/circuit/utils.ts:120]: Why is the downcast to number necessary?

File: src/circuit/utils.ts [hunk 5]
```diff
@@ -115,6 +115,10 @@ export async function namespaceToCid (namespace: string): Promise<CID> {
...
  * returns number of ms between now and expiration time
  */
-export function getExpiration (expireTime: bigint): number {
-  return Number(expireTime) - new Date().getTime()
+export function getExpirationMilliseconds (expireTimeSeconds: bigint): number {
+  const expireTimeMillis = expireTimeSeconds * BigInt(1000)
+  const currentTime = new Date().getTime()
+  // The difference between expireTime and currentTime is much more
+  // likely to fit in a Number type.
+  return Number(expireTimeMillis - BigInt(currentTime))
```
[the remark this answers is not in the document]
Comment (ckousik) [reply src/circuit/utils.ts:123]: We would have to downcast anyway to pass a duration to the setTimeout function.

**Comment by ckousik** [comment]
@achingbrain I've bounded the timeout duration between 30 seconds and 15 minutes. The values are arbitrary for now.

File: src/circuit/transport/reservation-store.ts [hunk 6]
```diff
@@ -23,6 +23,11 @@ const REFRESH_WINDOW = (60 * 1000) * 10
 // try to refresh relay reservations 5 minutes before expiry
 const REFRESH_TIMEOUT = (60 * 1000) * 5
 
+// maximum duration before which a reservation should be refereshed
```
Comment (achingbrain) [inline src/circuit/transport/reservation-store.ts:26]:
```suggestion
// maximum duration before which a reservation should be refreshed
```

File: src/circuit/transport/reservation-store.ts [hunk 7]
```diff
@@ -162,13 +167,18 @@ export class ReservationStore extends EventEmitter<ReservationStoreEvents> imple
 
         log('created reservation on relay peer %p', peerId)
 
-        const expiration = getExpiration(reservation.expire)
+        const expiration = getExpirationMilliseconds(reservation.expire)
+
+        // sets a lower bound on the timeout
+        const timeoutDuration = Math.max(expiration - REFRESH_TIMEOUT, REFRESH_TIMEOUT_MIN)
+        // sets an upper bound on the timeout
+        const boundedTimeoutDuration = Math.min(timeoutDuration, REFRESH_TIMEOUT_MAX)
```
Comment (achingbrain) [inline src/circuit/transport/reservation-store.ts:175]: If I'm reading this correctly `timeoutDuration` will either be `expiration - REFRESH_TIMEOUT` or `REFRESH_TIMEOUT_MIN`, (e.g. 30 seconds) whichever is greater.

Why do we need to then take the smaller value of `timeoutDuration` or `REFRESH_TIMEOUT_MAX ` (e.g. 15m)?

I think this means in the case where we get a reservation for an hour, we'll ignore the expiry time and refresh it after 15 minutes?

Can we not just use `timeoutDuration` having set a sensible lower bound?

Comment (achingbrain) [reply src/circuit/transport/reservation-store.ts:175]: Having said that, the [go implementation](https://github.com/libp2p/go-libp2p/blob/9e208249b588727cef726a7c2560a9db722404a1/p2p/protocol/circuitv2/client/reservation.go#L89-L91) just errors out if we receive a reservation expiration in the past, maybe that's better.

**Review by achingbrain — APPROVED** [review]
